---
- name: check for updates
  hosts: ser1
  become: true
  gather_facts: true

  tasks:
  - name: check for updates (yum)
    yum: list=updates update_cache=true
    register: yumoutput
  - debug: 
     msg: "{{ yumoutput.results | map(attribute='name') | list }}"
